name=PropertiesConfigLog4j2
property.filename=test-output/logs/app.log

appenders=console, file

# Console output
appender.console.type=Console
appender.console.name=STDOUT
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=[%-5level] %d{dd-MM-yyyy HH:mm:ss} [%t] %c{1} - %msg%n

# File output
appender.file.type=File
appender.file.name=LOGFILE
appender.file.fileName=${filename}
appender.file.layout.type=PatternLayout
appender.file.layout.pattern=[%-5level] %d{dd-MM-yyyy HH:mm:ss} [%t] %c{1} - %msg%n

# Named loggers (optional)
loggers=file
logger.file.name=LOGFILE
logger.file.level=info
logger.file.appenderRefs=file
logger.file.appenderRef.file.ref=LOGFILE

# Root logger (main)
rootLogger.level=info
rootLogger.appenderRefs=STDOUT, FILE
rootLogger.appenderRef.STDOUT.ref=STDOUT
rootLogger.appenderRef.FILE.ref=LOGFILE
